### PR TITLE
test for SearchBarListItem component

### PR DESCRIPTION
**Pull request by LubomyrKashuba**
## Description

Written tests for SearchBarListItem component  using React-testing-library #1555 

#### Screenshots

image

### Checklist

- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅All tests passed locally
- [x] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [x] 🔗 Link pull request to issue

### CODE REVIEW

**Review by AnastasiaKhukhra — COMMENTED** [review]
Please move tests to the general tests/unit/containers folder

**Review by AnastasiaKhukhra — APPROVED** [review]

**Comment by LubomyrKashuba** [comment]
> Please move tests to the general tests/unit/containers folder

done

**Comment by LubomyrKashuba** [comment]
> 

done

**Comment by LubomyrKashuba** [comment]
> Please move tests to the general tests/unit/containers folder

done

**Review by tarasSanotskyi — APPROVED** [review]

**Pull request merged**
