### PR TITLE
bugfix/1540/fix UI for authorization form

### PR DESCRIPTION
**Pull request by SirAndrii**
## Description

Fixed threw https://docs.google.com/spreadsheets/d/12P5AgSMLZywGaZsVRWR87HAODDG04-F7YM35R2qGeh4/edit#gid=1661224271

1. Refactored code of pages Login, GEnerate Password, Restore Password to meet the one standard.
2. Created new dumb components! Please revise the file structure for them.
3. Changed background 
4. Added adaptive design
5. Fixed unpretty loader Rectangle

#### Screenshots

|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** image ** | ** image ** |
MOBILE
|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** image** | ** ch1m** |

Fixed the Recovery Password Page
|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| **or3** | **ch3** |

Fixed Loader Background
|         Original          |         Updated          |
| :-----------------------: | :----------------------: |
| ** 
test2** | **test1** |
 
### Checklist

- [x] 🔽 My branch is up-to-date with "development" branch
- [x] ✅All tests passed locally
- [x] ✨My changes working with up-to-date admin and back-end part locally, like charm
- [x] 🔗 Link pull request to issue

### CODE REVIEW

**Comment by mrjnmzk** [comment]
Please clean code smells

**Comment by SirAndrii** [comment]
@mrjnmzk fixed code smells

**Comment by mrjnmzk** [comment]
hi please change header according to mockap 
image

**Comment by SirAndrii** [comment]
> hi please change header according to mockap when user move to recovery password page image

The header component is reused in all pages, it's rendered on the recovery page in the same way as on others. Need new issue to fix it like on the mockup one.

**Review by mrjnmzk — DISMISSED** [review]

**Comment by SirAndrii** [comment]
I moved files with tests and components to separated folders. Fixed problem with responsive design at 320px screen resolution that was mentioned by @DeLettenhove

**Review by DeLettenhove — APPROVED** [review]

**Review by byavdoshniak — APPROVED** [review]

**Pull request merged**
